"""empty message

Revision ID: 313822358ea9
Revises:
Create Date: 2020-12-09 15:23:52.248227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '313822358ea9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    ORDER_ENUM = sa.Enum("PLACED", 'APPROVED', 'DELIVERED', name="order_status", nullable=True)
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    #sa.Column('status', sa.Enum('PLACED', 'APPROVED', 'DELIVERED', name='order_status'), nullable=True),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.add_column("orders", sa.Column("status", ORDER_ENUM))

    PRODUCTS_ENUM = sa.Enum("AVAILABLE", 'PENDING', 'SOLD', name="product_status", nullable=True)
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('product_number', sa.Integer(), nullable=True),
    #sa.Column('status', sa.Enum('AVAILABLE', 'PENDING', 'SOLD', name='product_status'), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.add_column("products", sa.Column("status", PRODUCTS_ENUM))

    op.create_table('users',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('order_products',
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], )
    )
    op.create_table('users_orders',
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_orders')
    op.drop_table('order_products')
    op.drop_table('users')
    op.drop_table('products')
    op.drop_table('orders')
    # ### end Alembic commands ###
